### ISSUE TITLE
Suggest to restrict size of logo

### ISSUE THREAD

**Issue by JohnNiang** [xbf321/halo-theme-pure-black#1]
Please see the screenshot below:

<img width="897" alt="image" src="https://github.com/xbf321/halo-theme-pure-black/assets/16865714/6048701b-ad6b-4fa5-8732-3eadb810c583">

**Comment by xbf321** [comment]
v0.0.3 Fixed, thank you for your feedback.

**Comment by JohnNiang** [comment]
I confirmed that the issue was fixed by commit <https://github.com/xbf321/halo-theme-pure-black/commit/c31fa9add23e484c219a1403b0678472a43d521a>.
